import type { Metadata } from "next";
import Providers from "./providers";
import ToastProvider from "@/components/ToastProvider";
import BootstrapClient from "@/components/admin/BootstrapClient";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BootstrapClient />
        <Providers>
          {children}
          <ToastProvider />
        </Providers>
      </body>
    </html>
  );
}       
