import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import Header from "@/components/admin/Header";
import Footer from "@/components/admin/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  deScription: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Layout config Js */}
      {/* Bootstrap Css */}
      <link
        href="assets/backend/css/bootstrap.min.css"
        rel="stylesheet"
        type="text/css"
      />
      {/* Icons Css */}
      <link
        href="assets/backend/css/icons.min.css"
        rel="stylesheet"
        type="text/css"
      />
      {/* App Css*/}
      <link
        href="assets/backend/css/app.min.css"
        rel="stylesheet"
        type="text/css"
      />
      {/* custom Css*/}
      <link
        href="assets/backend/css/custom.min.css"
        rel="stylesheet"
        type="text/css"
      />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="layout-wrapper">
          <Header />
          {children}
          <Footer />
        </div>
        <Script src="assets/backend/libs/bootstrap/js/bootstrap.bundle.min.js"></Script>
        <Script src="assets/backend/libs/simplebar/simplebar.min.js"></Script>
        <Script src="assets/backend/libs/node-waves/waves.min.js"></Script>
        <Script src="assets/backend/libs/feather-icons/feather.min.js"></Script>
        <Script src="assets/backend/js/pages/plugins/lord-icon-2.1.0.js"></Script>
        <Script src="assets/backend/js/plugins.js"></Script>

        <Script src="assets/backend/libs/apexcharts/apexcharts.min.js"></Script>

        <Script src="assets/backend/libs/jsvectormap/jsvectormap.min.js"></Script>
        <Script src="assets/backend/libs/jsvectormap/maps/world-merc.js"></Script>

        <Script src="assets/backend/libs/swiper/swiper-bundle.min.js"></Script>

        <Script src="assets/js/pages/dashboard-ecommerce.init.js"></Script>

        <Script src="assets/js/app.js"></Script>
      </body>
    </html>
  );
}
